version: '3'

services:
  node-app:
    image: node:18-alpine3.18 # You can use any Node.js version you prefer
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm start"]
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - github-clone
    dns: 1.1.1.1

  github-clone:
    image: alpine/git
    volumes:
      - ./app:/app
    command: ["clone", "https://github.com/quacksire/ipps.git", "."]
    restart: "no"
    dns: 1.1.1.1
