version: '3'
services:
  node-app:
    image: node:14 # You can use any Node.js version you prefer
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm start"]
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - github-clone

  github-clone:
    image: alpine/git
    volumes:
      - ./app:/app
    command: ["git", "clone", "https://github.com/quacksire/ipps.git", "."]
    restart: "no"
