version: '3'
services:
  node-app:
    image: node:14 # You can use any Node.js version you prefer
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - github-clone

  github-clone:
    image: alpine/git
    volumes:
      - ./app:/app
    command: ["git", "clone", "https://github.com/quacksire/ipps", "."]
    restart: "no"
    depends_on:
      - wait-for-git

  wait-for-git:
    image: alpine:latest
    command: ["sh", "-c", "while [ ! -d /app/.git ]; do sleep 1; done"]
    depends_on:
      - node-app

  install-packages:
    image: node:14 # You can use any Node.js version you prefer
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["npm", "install"]
    restart: "no"
    depends_on:
      - github-clone

  wait-for-node:
    image: alpine:latest
    command: ["sh", "-c", "while ! nc -z node-app 3000; do sleep 1; done"]
    depends_on:
      - install-packages
